'''
Create an alphabet.pkl file from a count list,
an alphabet size, and number of unknown tokens to consider.
'''

import json
import pickle
import argparse
from alphabet import Alphabet

parser = argparse.ArgumentParser(description='Preprocess Wikipedia data generated by wikiparse')
parser.add_argument('--size', type=int, dest='size', help='Size of the resulting alphabet')
parser.add_argument('--unk', type=int, dest='unk', help='Number of unknown tokens to allot indices for')
parser.add_argument('--counts',  dest='counts_file', help='Counts file')
parser.add_argument('--out', dest='out_file', help='Output file')

args = parser.parse_args()

with open(args.counts_file) as f:
  all_tokens = json.load(f)
  alphabet = Alphabet(list(map(lambda x: x[0], all_tokens[:args.size])), args.unk)
  with open(args.out_file, 'wb') as o:
    pickle.dump(alphabet, o)
